name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.402
    - name: Build with dotnet
      run: dotnet build --configuration Release
    - name: Docker Setup Buildx
      # You may pin to the exact commit or the version.
      # uses: docker/setup-buildx-action@0d135e0c2fc0dba0729c1a47ecfcf5a3c7f8579e
      uses: docker/setup-buildx-action@v1.3.0     
    - name: Docker Buildx Bake
  # You may pin to the exact commit or the version.
  # uses: docker/bake-action@1882cef5add2e6021b30cd4c565b9afd664f5251
      uses: docker/bake-action@v1.4.0
