name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['5.0.x' ]

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Publish
      run: dotnet publish 
      
    - name: Zip Release
      # You may pin to the exact commit or the version.
      # uses: TheDoctor0/zip-release@a1afcab9c664c9976ac398fa831eac67bed1eb0e
      uses: TheDoctor0/zip-release@0.4.1
      with:
        # Filename for archive
        filename: randomquotes.1.1
        # Base path for archive files
    
    - name: Install Octopus CLI
      # You may pin to the exact commit or the version.
      # uses: OctopusDeploy/install-octopus-cli-action@aee5b620e9107e6ef3ae0cbd25dfde10e0910168
      uses: OctopusDeploy/install-octopus-cli-action@v1.1.6
      
    - name: Push Package to Octopus Deploy
  # You may pin to the exact commit or the version.
  # uses: OctopusDeploy/push-package-action@db2b64b77368373659086c2b2631b02019fdcca0
      uses: OctopusDeploy/push-package-action@v1.0.1
      with:
        # The API key used to access Octopus Deploy. You must provide an API key or username and password. If the guest account is enabled, a key of API-GUEST may be used. It is strongly recommended that this value retrieved from a GitHub secret.
        api_key: ${{secrets.OCTOPUSAPI}}
        # Enable debug logging.
        debug: false
        # Ignore certificate errors when communicating with Octopus Deploy. Warning: enabling this option creates a security vulnerability.
        ignore_ssl_errors: false
        # The log level; valid options are "verbose", "debug", "information", "warning", "error", and "fatal".
        log_level: verbose
        # Determines the action to perform with package if it already exists in the repository. Valid values are "FailIfExists", "OverwriteExisting", and "IgnoreIfExists".
        overwrite_mode: OverwriteExisting
        # A comma-delimited list of packages to push to Octopus Deploy (i.e. package1,package2).
        packages: randomquotes.1.1.zip
        # The base URL hosting Octopus Deploy (i.e. "https://octopus.example.com/"). It is recommended to retrieve this value from an environment variable.
        server: https://octopuscb.eastus.cloudapp.azure.com/

    
